name: e-bot7 helm chart value updater
description: Create a PR to update a helm chart's value.
inputs:
  repository:
    required: true
    description: The repository with the helm chart values file.
  file_path:
    required: true
    description: The path of the yaml file to be updated, relative to the repository root.
  key:
    required: true
    description: The key to be updated in the file.
    example: '.myApp.image.tag'
  value:
    required: true
    description: The value to set for the given key.
  token:
    required: true
    description: The token used to checkout the repo and create the PR.
  auto_merge:
    default: false
    description: Whether to enable automatic merging for the PR.

runs:
    using: composite
    steps:
      - name: Clone remote repository
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          token: ${{ inputs.token }}

      - name: Update the value in the yaml file
        shell: bash
        run: |
          yq e -i '${{ inputs.key }} = "${{ inputs.value }}"' ${{ inputs.file_path }}

          git checkout -b autoupdate-${{ inputs.file_path }}

          git config user.name ${{ github.actor }}
          git config user.email "${{ github.actor }}@users.noreply.github.com>"
          git commit \
          -m "Updating ${{ inputs.key }} to ${{ inputs.value }} in ${{ inputs.file_path }}" \
          ${{ inputs.file_path }}

          git push --set-upstream origin autoupdate-${{ inputs.file_path }}

      - name: Create automated Pull Request
        shell: bash
        env:
          GITHUB_TOKEN: ${{ inputs.token }}
        run: |
          gh pr create --fill

          if gh pr checks
          then
            # All checks are passing, merge.
            gh pr merge --rebase --delete
          else
            gh pr merge --auto --rebase --delete
          fi
